const text = [
  `Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
  `Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy shoreditch 8-bit microdosing, XOXO viral butcher banh mi humblebrag listicle woke bicycle rights brunch before they sold out ramps. Twee shabby chic taiyaki flannel, enamel pin venmo vape four loko. Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical banh mi narwhal echo park cronut.`,
  `Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.`,
  `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
  `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
  `Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
  `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
  `Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
  `Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
  `I'm baby cornhole kale chips venmo PBR&B, next level beard bushwick hammock cold-pressed franzen shabby chic banh mi tumblr crucifix pickled. Knausgaard street art 8-bit YOLO lumbersexual occupy, hammock blue bottle tattooed cray edison bulb poutine helvetica food truck. Viral four dollar toast biodiesel kale chips beard. Selfies pabst bespoke chartreuse godard freegan raw denim. Pork belly kombucha schlitz, butcher shoreditch synth taxidermy hexagon photo booth venmo. Tattooed humblebrag shoreditch, synth chartreuse venmo selvage try-hard portland. Green juice trust fund hexagon tote bag direct trade normcore.`,
  `Hashtag waistcoat austin, yr tilde occupy cronut kogi. Meggings man braid paleo poke, blue bottle gochujang woke williamsburg vegan vaporware cornhole sustainable activated charcoal kale chips raw denim. Echo park hella shabby chic, sartorial biodiesel poutine vegan yr edison bulb. Vape paleo synth lo-fi, twee vegan swag coloring book. Leggings single-origin coffee intelligentsia, fixie occupy gentrify succulents. Trust fund bicycle rights fashion axe polaroid small batch tattooed.`,
  `Forage knausgaard flannel venmo dreamcatcher la croix. Disrupt snackwave fanny pack thundercats, cray post-ironic lumbersexual venmo etsy whatever yuccie try-hard +1. Waistcoat PBR&B mixtape deep v shabby chic messenger bag typewriter. Migas fingerstache cred beard, man braid schlitz man bun ennui palo santo synth. Pinterest af bushwick banjo offal cloud bread.`,
  `Pabst try-hard kitsch flannel. Mustache tote bag twee church-key. Retro skateboard deep v direct trade kogi fanny pack quinoa edison bulb woke cronut distillery. Hell of live-edge mlkshk franzen sartorial vaporware pitchfork. Trust fund blog authentic heirloom tacos cloud bread tilde raclette knausgaard.`,
  `Celiac edison bulb williamsburg fam. Shoreditch ethical butcher pickled pug health goth chillwave pop-up tacos jianbing. Gochujang DIY schlitz copper mug microdosing pour-over hammock pok pok iPhone biodiesel trust fund af sartorial. Snackwave helvetica master cleanse paleo yuccie, organic freegan pinterest crucifix gochujang. Swag sriracha marfa skateboard, scenester enamel pin poke brooklyn flannel bushwick kinfolk thundercats everyday carry shabby chic flexitarian.`,
  `Bitters before they sold out celiac art party beard. Deep v kickstarter jianbing plaid air plant, brunch you probably haven't heard of them forage chartreuse slow-carb farm-to-table tumeric chillwave master cleanse. Migas pour-over freegan 3 wolf moon locavore four loko. Portland microdosing selfies banh mi hoodie twee. Fixie mustache poutine +1 unicorn kinfolk twee wayfarers chia bitters forage. Pinterest street art prism vexillologist blog, lo-fi roof party semiotics knausgaard ethical glossier shabby chic vinyl.`,
  `Messenger bag distillery edison bulb cray woke twee DIY forage cronut yr pickled kale chips chicharrones. Poutine retro before they sold out woke prism venmo put a bird on it church-key banjo vaporware typewriter chillwave butcher humblebrag. Aesthetic asymmetrical glossier sartorial irony. Tousled pork belly glossier, hoodie tilde everyday carry vegan. Pop-up authentic vegan, narwhal VHS intelligentsia kogi cred vice. Kombucha tofu chambray authentic, XOXO bespoke woke brooklyn meggings.`,
  `Pork belly tilde tattooed, sriracha vaporware palo santo keffiyeh hashtag tofu quinoa drinking vinegar iPhone XOXO. Truffaut pok pok kogi franzen subway tile hella. Ramps taxidermy gastropub prism, hoodie distillery truffaut poutine 3 wolf moon lo-fi leggings. Vape small batch photo booth knausgaard etsy food truck. Cred tumblr disrupt, typewriter street art raclette gentrify tilde ugh yuccie roof party thundercats viral.`,
  `Mixtape ramps jean shorts roof party, man braid raclette yuccie occupy bitters banjo swag wayfarers direct trade cornhole godard. Pitchfork four dollar toast venmo distillery, locavore polaroid affogato air plant flannel helvetica migas occupy yr you probably haven't heard of them bicycle rights. Letterpress gentrify pop-up, master cleanse echo park hashtag affogato tbh food truck fingerstache bicycle rights 8-bit ugh offal prism. Flexitarian tumblr pabst lyft gochujang taiyaki snackwave la croix cray pug occupy umami offal. Meh you probably haven't heard of them jianbing cronut brunch portland stumptown put a bird on it copper mug.`,
  `Try-hard man braid small batch kitsch yuccie blue bottle, +1 enamel pin. Cliche ugh man bun af. Next level lo-fi banjo cronut kale chips tumeric. Next level DIY trust fund snackwave 3 wolf moon beard. Gochujang chillwave street art fashion axe, flannel venmo iPhone green juice skateboard kickstarter bespoke man braid man bun live-edge ethical. Subway tile vinyl art party taxidermy chicharrones asymmetrical, tattooed ugh PBR&B vaporware whatever poutine retro vape salvia. Af iceland pok pok man braid, gastropub meh authentic ramps 3 wolf moon hell of vice.`,
  `Wayfarers vexillologist fam, umami messenger bag poke post-ironic. Vinyl quinoa letterpress single-origin coffee, taxidermy jean shorts hella lyft lomo kogi four dollar toast cliche gastropub. Shabby chic semiotics microdosing, blog cray mixtape lo-fi yr. Marfa actually distillery chartreuse skateboard selfies XOXO cold-pressed. Bushwick post-ironic beard, kogi seitan irony before they sold out dreamcatcher sustainable.`
];
export default text;
